# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts

# Miscellaneous
google_analytics: 
favicon: /favicon.ico
twitter: 
google_plus:
fb_admins:
fb_app_id: