# Header
menu:
  主页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tagcloud
- weibo

# Miscellaneous
google_analytics: 
favicon: /H.png
twitter: 
google_plus:
fb_admins:
fb_app_id: